---
title: "Recognition Plots"
author: "Gözem Turan"
date: "29 6 2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(lme4)
library(car)
library(tidyr)
library(Rmisc)
library(rstatix)
library(dplyr)
library(ggpubr)
library(ggplot2)
library(ez)
library(psycho)
library(sjPlot)
library(PupillometryR)
library(MetBrewer)
library(here)
```

# Open data seperately
```{r}
# setting relative path
here_path <- here()

# relative data path
data_path <- file.path(here_path, "data", "raw_data")

# reading the data in
df_m <- read.csv(file = file.path(data_path, "m_part3_rt_out.csv"))
df_w <- read.csv(file = file.path(data_path, "w_part3_rt_out.csv"))
```

Preparations for df_m
```{r}
# setting pe as a factor
df_m <- df_m %>% 
  mutate(pe = factor(pe, levels = c("lowPE", "medPE", "highPE")))

# setting participant to a factor variable
df_m <- df_m %>% 
  mutate(participant = as.factor(participant))

# setting confidence to a factor variable
df_m <- df_m %>% 
  mutate(conf = factor(conf, levels = c("1", "2", "3", "4")))

# removing NA values from the dataframe
df_m <- df_m %>% 
  na.omit()

# creating column with all values as "Experiment 2"
df_m <- df_m %>% 
  mutate(study = "Experiment 1") 
```

# preparations for df_w
```{r}
# change the naming for PE levels to be consistend
df_w <- df_w %>%
  mutate(pe = recode(PE_level, low = "lowPE", medium = "medPE", high = "highPE"))

# converting pe to a factor variable
df_w$pe <- factor(df_w$pe, levels = c("lowPE", "medPE", "highPE")) # pe

# setting participant to a factor variable
df_w$participant <- as.factor(df_w$participant) # participants

# setting confidence to a factor variable
df_w$conf <- factor(df_w$conf, levels = c("1", "2", "3", "4")) # confidence

# removing NA values from the dataframe
df_w <- na.omit(df_w)

# creating column with all values as "Experiment 2"
df_w$study <- c("Experiment 2")
```

# Combine two data sets
```{r}
# combining the two dataframes 
# will set NA values to any columns that one dataset does not have
df <- bind_rows(df_m, df_w)
# just ignore the na values

# setting study as a factor variable
df <- df %>% 
  mutate(study = as.factor(study))
```

# Aggregated data
```{r}
# creates a summary dataframe of the corrAns varible (count, mean, sd, se, ci)
# grouped by pe and study
df_corr_ans <- df %>% 
  group_by(pe, study) %>% 
  summarise(
    N = n(),
    mean_corr_ans = mean(corrAns, na.rm = TRUE),
    sd = sd(corrAns, na.rm = TRUE),
    se = sd / sqrt(N)
  ) 

# creates a summary dataframe of the corrAns varible (count, mean, sd, se, ci)
# grouped by pe, participant, and study
df_corr_ans_part <- 
  group_by(pe, participant, study) %>% 
  summarise(
    N = n(),
    mean_corr_ans = mean(corrAns, na.rm = TRUE),
    sd = sd(corrAns, na.rm = TRUE),
    se = sd / sqrt(N)
  )

```

# First plot - Rainyclouds
```{r}

# Violin plot of hit responses as a function of pe level, for Experiments 1 and 2
ggplot(df_corr_ans_part, aes(x = pe, y = mean_corr_ans, fill = pe)) +
  geom_flat_violin(position = position_nudge(x = .1, y = 0), adjust = 1.5, trim = TRUE, color = "white") +
  geom_point(aes(x = as.numeric(pe) - .15, y = mean_corr_ans), position = position_jitter(width = .05, height = 0), size = 1, shape = 20) +
  # box plot
  # geom_boxplot(aes(x = pe, y = mean_corr_ans),outlier.shape = NA, width = .1, colour = "black") +
  geom_errorbar(data = df_corr_ans, aes(ymin = mean_corr_ans - se, ymax = mean_corr_ans + se, width = 0.1)) +
  geom_point(data = df_corr_ans, size = 1) +
  geom_line(data = df_corr_ans, aes(x = pe, y = mean_corr_ans), size = 0.5, group = 1) +
  theme_classic() +
  scale_fill_manual(values = met.brewer("Derain", 5, type = "continuous")) +
  scale_color_manual(values = met.brewer("Derain", 5, type = "continuous")) +
  scale_x_discrete(name = "PE Level", 
                   labels = c("lowPE" = "Low", "medPE" = "Medium", "highPE" = "High")) +
  theme(
    text = element_text(family = "TT Times New Roman", size = 15), 
    legend.title = element_text(size = 1), 
    legend.text = element_text(size = 12), 
    legend.position = "None", 
    legend.direction = "vertical") +
  ylab("Hit Responses") +
  ylim(0, 1) +
  # geom_signif(comparisons = list(c("lowPE", "highPE")), map_signif_level=TRUE, y_position = c(1.1, 1.2, 1.3)) +
  facet_wrap(. ~ study)

```

# Second plot - spaghetti & box & distribution
```{r}

# Hit rate per person across different levels of pe, per each experiment
ggplot(df_corr_ans_part, aes(x = 1, y = mean_corr_ans, fill = pe)) +
  geom_flat_violin(trim = TRUE, position = position_nudge(x = 2.3), alpha = .9, color = "black") +
  geom_point(aes(x = factor(pe), y = mean_corr_ans, fill = factor(pe)), size = 2.5, shape = 21) +
  geom_line(aes(x = factor(pe), y = mean_corr_ans, group = participant)) +
  geom_boxplot(
    width = .1, show.legend = FALSE,
    outlier.shape = NA, alpha = .9,
    position = position_nudge(x = 2.2)
  ) +
  # geom_line(data=df_corr_ans, aes(x=pe, y=mean_corr_ans), size=1.4, group=1, color = "pink") +
  scale_fill_manual(values = met.brewer("Derain", 5, type = "continuous")) +
  theme_classic() +
  scale_x_discrete(name = "PE Level", labels = c("lowPE" = "Low", "medPE" = "Medium", "highPE" = "High")) +
  theme(
    text = element_text(family = "TT Times New Roman", size = 15), 
    legend.title = element_text(size = 1), 
    legend.text = element_text(size = 12), 
    legend.position = "None", 
    legend.direction = "vertical") +
  ylab("Hit Responses") +
  ylim(0, 1) +
  # geom_signif(comparisons = list(c("low", "dprimeMed"), c("dprimeLow", "dprimeHigh"), c("dprimeMed", "dprimeHigh")), map_signif_level=TRUE) +
  facet_wrap(. ~ study)
```


# Third plot - violin
```{r}

# Plot of hit rate as a function of pe level, per each experiment
# Significance shown for low vs. high pe level
ggplot(df_corr_ans_part, aes(x = pe, y = mean_corr_ans, fill = pe)) +
  geom_violin(color = "white", trim = TRUE) +
  geom_jitter(aes(x = pe, y = mean_corr_ans, group = participant, alpha = 0.5), color = "gray50", size = 0.5, position = position_dodge(0)) +
  geom_line(aes(x = pe, y = mean_corr_ans, group = participant, alpha = 0.5), color = "gray50", position = position_dodge(0)) +
  geom_point(data = df_corr_ans, size = 1) +
  geom_errorbar(data = df_corr_ans, aes(ymin = mean_corr_ans - se, ymax = mean_corr_ans + se, width = 0.1)) +
  geom_line(data = df_corr_ans, aes(x = pe, y = mean_corr_ans), size = 0.9, group = 1) +
  scale_x_discrete(name = "PE Level", labels = c("lowPE" = "Low", "medPE" = "Medium", "highPE" = "High")) +
  scale_fill_manual(values = met.brewer("Derain", 5, type = "continuous")) +
  theme_classic() +
  theme(text = element_text(family = "TT Times New Roman", size = 15), legend.title = element_text(size = 1), legend.text = element_text(size = 12), legend.position = "None", legend.direction = "vertical") +
  ylab("Hit Responses") +
  # ylim(0, 1) +
  geom_signif(comparisons = list(c("highPE", "lowPE")), map_signif_level = FALSE) +
  facet_wrap(. ~ study)
```


# CONFINDENCE 
```{r}

# Summary statistics for mean_corr_ans variable, grouped by pe, study, and conf
df_corr_ans_conf <- summarySE(df,
  measurevar = "corrAns", 
  groupvars = c("pe", "study", "conf"), na.rm = TRUE)

## Summary statistics for corrAns variable, grouped by pe, participant, study, and conf
df_corr_ans_all <- summarySE(df,
  measurevar = "corrAns",
  groupvars = c("pe", "participant", "conf", "study"), na.rm = TRUE
)
```

PLOT
```{r}
# Violin plot of hit rate as a function of pe, grouped by confidence levels
ggplot(df_corr_ans_all, aes(x = pe, y = mean_corr_ans, fill = pe)) +
  geom_violin(color = "white", trim = TRUE) +
  geom_jitter(aes(x = pe, y = mean_corr_ans, group = participant, alpha = 0.5), color = "gray50", size = 0.5, position = position_dodge(0)) +
  geom_line(aes(x = pe, y = mean_corr_ans, group = participant, alpha = 0.5), color = "gray50", position = position_dodge(0)) +
  geom_point(data = df_corr_ans_conf, size = 1) +
  geom_errorbar(data = df_corr_ans_conf, aes(ymin = mean_corr_ans - se, ymax = mean_corr_ans + se, width = 0.1)) +
  geom_line(data = df_corr_ans_conf, aes(x = pe, y = mean_corr_ans), size = 0.9, group = 1) +
  scale_x_discrete(name = "PE Level", labels = c("lowPE" = "Low", "medPE" = "Medium", "highPE" = "High")) +
  scale_fill_manual(values = met.brewer("Derain", 5, type = "continuous")) +
  theme_classic() +
  theme(
    text = element_text(family = "TT Times New Roman", size = 15), 
    legend.title = element_text(size = 1), 
    legend.text = element_text(size = 12), 
    legend.position = "None", 
    legend.direction = "vertical") +
  ylab("Hit Responses") +
  ylim(0, 1) +
  # geom_signif(comparisons = list(c("low", "dprimeMed"), c("dprimeLow", "dprimeHigh"), c("dprimeMed", "dprimeHigh")), map_signif_level=TRUE) +
  facet_grid(conf ~ study)
```
